import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GSAP 101',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
      className={inter.className}
      style={{
        display:"flex",
        flexDirection:"column",
        alignItems:"center",
        padding:"1rem"
      }}>{children}</body>
    </html>
  )
}
